# Generated by Django 5.2.8 on 2026-08-20 22:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_comment_follow_like'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserOwnedGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ownership_type', models.CharField(choices=[('FISICO', 'Físico'), ('DIGITAL', 'Digital')], default='FISICO', max_length=10)),
                ('completed', models.BooleanField(default=False, verbose_name='Já zerei?')),
                ('acquired_at', models.DateField(blank=True, null=True, verbose_name='Data de aquisição')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('game_catalog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_copies', to='api.gamecatalog')),
                ('platform', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_owned_games', to='api.platform')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_games', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Jogo da coleção',
                'verbose_name_plural': 'Jogos da coleção',
                'constraints': [models.UniqueConstraint(fields=('user', 'game_catalog', 'platform', 'ownership_type'), name='unique_owned_game_copy')],
            },
        ),
    ]
