# Generated by Django 5.2.8 on 2026-08-21 15:08

import api.models
import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_userownedgame'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BoardGameCatalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bgg_id', models.PositiveIntegerField(blank=True, null=True, unique=True, verbose_name='ID BoardGameGeek')),
                ('name', models.CharField(max_length=250)),
                ('original_name', models.CharField(blank=True, max_length=250, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='boardgames/covers/')),
                ('cover_url', models.URLField(blank=True, max_length=1000, null=True)),
                ('thumbnail_url', models.URLField(blank=True, max_length=1000, null=True)),
                ('year', models.PositiveIntegerField(blank=True, null=True)),
                ('min_players', models.PositiveIntegerField(blank=True, null=True)),
                ('max_players', models.PositiveIntegerField(blank=True, null=True)),
                ('min_play_time', models.PositiveIntegerField(blank=True, null=True)),
                ('max_play_time', models.PositiveIntegerField(blank=True, null=True)),
                ('min_age', models.PositiveIntegerField(blank=True, null=True)),
                ('publisher', models.CharField(blank=True, max_length=250, null=True)),
                ('categories', models.JSONField(blank=True, default=list)),
                ('mechanics', models.JSONField(blank=True, default=list)),
                ('designers', models.JSONField(blank=True, default=list)),
                ('artists', models.JSONField(blank=True, default=list)),
                ('publishers', models.JSONField(blank=True, default=list)),
                ('bgg_rating', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('bgg_weight', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Complexidade BGG')),
                ('rules', models.TextField(blank=True, null=True)),
                ('imported_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Jogo de tabuleiro - catálogo',
                'verbose_name_plural': 'Jogos de tabuleiro - catálogo',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='UserBoardGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owned', models.BooleanField(default=False, verbose_name='Tenho este jogo?')),
                ('played', models.BooleanField(default=True, verbose_name='Já joguei?')),
                ('rating', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.0')), django.core.validators.MaxValueValidator(Decimal('10.0')), api.models.validate_half_step], verbose_name='Minha nota')),
                ('acquired_at', models.DateField(blank=True, null=True, verbose_name='Data de aquisição')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_entries', to='api.boardgamecatalog')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='board_game_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Jogo de tabuleiro do usuário',
                'verbose_name_plural': 'Jogos de tabuleiro do usuário',
                'ordering': ['game__name'],
                'constraints': [models.UniqueConstraint(fields=('user', 'game'), name='unique_user_board_game')],
            },
        ),
    ]
