# Generated by Django 5.2.8 on 2026-08-25 17:59

import api.models
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_boardgamecatalog_userboardgame'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='console',
            options={'ordering': ['platform__name']},
        ),
        migrations.AlterModelOptions(
            name='gamecatalog',
            options={'ordering': ['title'], 'verbose_name': 'Jogo - catálogo IGDB', 'verbose_name_plural': 'Jogos - catálogo IGDB'},
        ),
        migrations.AlterModelOptions(
            name='platform',
            options={'ordering': ['name']},
        ),
        migrations.AlterUniqueTogether(
            name='usergameentry',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='console',
            name='name',
        ),
        migrations.RemoveField(
            model_name='console',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='gamecatalog',
            name='api_id',
        ),
        migrations.RemoveField(
            model_name='gamecatalog',
            name='cover_image',
        ),
        migrations.RemoveField(
            model_name='gamecatalog',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='gamecatalog',
            name='genre',
        ),
        migrations.RemoveField(
            model_name='gamecatalog',
            name='platform',
        ),
        migrations.RemoveField(
            model_name='platform',
            name='platform_image',
        ),
        migrations.AddField(
            model_name='console',
            name='acquired_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='console',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='console',
            name='platform',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='owned_by_users', to='api.platform'),
        ),
        migrations.AddField(
            model_name='gamecatalog',
            name='aggregated_rating',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='gamecatalog',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gamecatalog',
            name='developers',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='gamecatalog',
            name='genres',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='gamecatalog',
            name='igdb_id',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='gamecatalog',
            name='igdb_rating',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='gamecatalog',
            name='imported_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gamecatalog',
            name='platforms',
            field=models.ManyToManyField(blank=True, related_name='games', to='api.platform'),
        ),
        migrations.AddField(
            model_name='gamecatalog',
            name='publishers',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='gamecatalog',
            name='slug',
            field=models.SlugField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='gamecatalog',
            name='storyline',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gamecatalog',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='platform',
            name='abbreviation',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='platform',
            name='generation',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='platform',
            name='igdb_id',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='platform',
            name='logo_url',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='platform',
            name='slug',
            field=models.SlugField(blank=True, max_length=180, null=True),
        ),
        migrations.AddField(
            model_name='platform',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='usergameentry',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='userownedgame',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='console',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_consoles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='gamecatalog',
            name='cover_url',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='gamecatalog',
            name='release_year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gamecatalog',
            name='title',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='platform',
            name='name',
            field=models.CharField(max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='usergameentry',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.0')), django.core.validators.MaxValueValidator(Decimal('10.0')), api.models.validate_half_step]),
        ),
        migrations.AddConstraint(
            model_name='console',
            constraint=models.UniqueConstraint(fields=('user', 'platform'), name='unique_user_console'),
        ),
        migrations.AddConstraint(
            model_name='usergameentry',
            constraint=models.UniqueConstraint(fields=('user', 'game_catalog'), name='unique_user_game_entry'),
        ),
    ]
