# Generated by Django 5.2.8 on 2026-08-26 14:54

import api.models
import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_console_options_alter_gamecatalog_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LibraryCatalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('openlibrary_key', models.CharField(blank=True, max_length=150, null=True, unique=True)),
                ('edition_key', models.CharField(blank=True, max_length=150, null=True)),
                ('title', models.CharField(max_length=300)),
                ('subtitle', models.CharField(blank=True, max_length=300, null=True)),
                ('item_type', models.CharField(choices=[('LIVRO', 'Livro'), ('HQ', 'HQ'), ('MANGA', 'Mangá'), ('REVISTA', 'Revista'), ('OUTRO', 'Outro')], default='LIVRO', max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('authors', models.JSONField(blank=True, default=list)),
                ('publishers', models.JSONField(blank=True, default=list)),
                ('first_publish_year', models.PositiveIntegerField(blank=True, null=True)),
                ('publication_year', models.PositiveIntegerField(blank=True, null=True)),
                ('isbn', models.CharField(blank=True, max_length=30, null=True)),
                ('cover_url', models.URLField(blank=True, max_length=1000, null=True)),
                ('subjects', models.JSONField(blank=True, default=list)),
                ('languages', models.JSONField(blank=True, default=list)),
                ('page_count', models.PositiveIntegerField(blank=True, null=True)),
                ('imported_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Obra - catálogo da biblioteca',
                'verbose_name_plural': 'Obras - catálogo da biblioteca',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='UserLibraryEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owned', models.BooleanField(default=False, verbose_name='Tenho esta obra?')),
                ('ownership_type', models.CharField(blank=True, choices=[('FISICO', 'Físico'), ('DIGITAL', 'Digital')], max_length=10, null=True, verbose_name='Formato')),
                ('reading_status', models.CharField(choices=[('NAO_LIDO', 'Não lido'), ('LENDO', 'Lendo'), ('LIDO', 'Lido'), ('PAUSADO', 'Pausado'), ('QUERO_LER', 'Quero ler')], default='NAO_LIDO', max_length=15, verbose_name='Status de leitura')),
                ('rating', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.0')), django.core.validators.MaxValueValidator(Decimal('10.0')), api.models.validate_half_step], verbose_name='Minha nota')),
                ('acquired_at', models.DateField(blank=True, null=True, verbose_name='Data de aquisição')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_entries', to='api.librarycatalog')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='library_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Obra da biblioteca do usuário',
                'verbose_name_plural': 'Obras da biblioteca do usuário',
                'ordering': ['item__title'],
                'constraints': [models.UniqueConstraint(fields=('user', 'item'), name='unique_user_library_entry')],
            },
        ),
    ]
