# Generated by Django 5.2.8 on 2026-09-02 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_librarycatalog_isbn'),
    ]

    operations = [
        migrations.AddField(
            model_name='librarycatalog',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='librarycatalog',
            name='issue_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='librarycatalog',
            name='series_name',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='librarycatalog',
            name='source',
            field=models.CharField(blank=True, choices=[('OPEN_LIBRARY', 'Open Library'), ('GCD', 'Grand Comics Database'), ('COMIC_VINE', 'Comic Vine'), ('GOOGLE_BOOKS', 'Google Books'), ('MANUAL', 'Cadastro manual')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='librarycatalog',
            name='source_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddConstraint(
            model_name='librarycatalog',
            constraint=models.UniqueConstraint(condition=models.Q(('source__isnull', False), ('source_id__isnull', False)), fields=('source', 'source_id'), name='unique_library_source_item'),
        ),
    ]
