# Generated by Django 5.2.8 on 2026-09-02 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_librarycatalog_country_librarycatalog_issue_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='librarycatalog',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='library/covers/'),
        ),
    ]
