# Generated by Django 5.2.8 on 2026-09-02 14:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_librarycatalog_cover_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BeyBit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('abbreviation', models.CharField(blank=True, max_length=20, null=True)),
                ('bit_type', models.CharField(choices=[('ATAQUE', 'Ataque'), ('DEFESA', 'Defesa'), ('STAMINA', 'Stamina'), ('BALANCE', 'Balance')], max_length=20)),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='beyblade/bits/')),
                ('image_url', models.URLField(blank=True, max_length=1000, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BeyBlade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('code', models.CharField(blank=True, max_length=50, null=True)),
                ('bey_type', models.CharField(choices=[('ATAQUE', 'Ataque'), ('DEFESA', 'Defesa'), ('STAMINA', 'Stamina'), ('BALANCE', 'Balance')], max_length=20)),
                ('spin', models.CharField(choices=[('RIGHT', 'Direita'), ('LEFT', 'Esquerda'), ('DUAL', 'Dual Spin')], default='RIGHT', max_length=10)),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='beyblade/blades/')),
                ('image_url', models.URLField(blank=True, max_length=1000, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BeyRatchet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('height', models.PositiveIntegerField(blank=True, null=True)),
                ('protrusions', models.PositiveIntegerField(blank=True, null=True)),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='beyblade/ratchets/')),
                ('image_url', models.URLField(blank=True, max_length=1000, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BeybladeBuild',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150, null=True)),
                ('favorite', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='builds', to='api.beybit')),
                ('blade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='builds', to='api.beyblade')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beyblade_builds', to=settings.AUTH_USER_MODEL)),
                ('ratchet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='builds', to='api.beyratchet')),
            ],
            options={
                'ordering': ['-favorite', 'blade__name'],
            },
        ),
        migrations.CreateModel(
            name='UserBeyBit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('acquired_at', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('bit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_by_users', to='api.beybit')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_bey_bits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'bit'), name='unique_user_bey_bit')],
            },
        ),
        migrations.CreateModel(
            name='UserBeyBlade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('acquired_at', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('blade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_by_users', to='api.beyblade')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_bey_blades', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'blade'), name='unique_user_bey_blade')],
            },
        ),
        migrations.CreateModel(
            name='UserBeyRatchet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('acquired_at', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('ratchet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_by_users', to='api.beyratchet')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_bey_ratchets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'ratchet'), name='unique_user_bey_ratchet')],
            },
        ),
    ]
