# Generated by Django 5.2.8 on 2026-09-02 15:38

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_beybit_beyblade_beyratchet_beybladebuild_userbeybit_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BeyAssistBlade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='beyblade/assist-blades/')),
                ('image_url', models.URLField(blank=True, max_length=1000, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Assist Blade',
                'verbose_name_plural': 'Assist Blades',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BeyLockChip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='beyblade/lock-chips/')),
                ('image_url', models.URLField(blank=True, max_length=1000, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Lock Chip',
                'verbose_name_plural': 'Lock Chips',
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='beybit',
            options={'ordering': ['name'], 'verbose_name': 'Bit', 'verbose_name_plural': 'Bits'},
        ),
        migrations.AlterModelOptions(
            name='beyblade',
            options={'ordering': ['name'], 'verbose_name': 'Blade', 'verbose_name_plural': 'Blades'},
        ),
        migrations.AlterModelOptions(
            name='beybladebuild',
            options={'ordering': ['-favorite', 'blade__name'], 'verbose_name': 'Build Beyblade', 'verbose_name_plural': 'Builds Beyblade'},
        ),
        migrations.AlterModelOptions(
            name='beyratchet',
            options={'ordering': ['name'], 'verbose_name': 'Ratchet', 'verbose_name_plural': 'Ratchets'},
        ),
        migrations.AlterModelOptions(
            name='userbeybit',
            options={'ordering': ['bit__name'], 'verbose_name': 'Bit do usuário', 'verbose_name_plural': 'Bits do usuário'},
        ),
        migrations.AlterModelOptions(
            name='userbeyblade',
            options={'ordering': ['blade__name'], 'verbose_name': 'Blade do usuário', 'verbose_name_plural': 'Blades do usuário'},
        ),
        migrations.AlterModelOptions(
            name='userbeyratchet',
            options={'ordering': ['ratchet__name'], 'verbose_name': 'Ratchet do usuário', 'verbose_name_plural': 'Ratchets do usuário'},
        ),
        migrations.AddField(
            model_name='beybit',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='beybit',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='beyratchet',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='beyratchet',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='userbeybit',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userbeybit',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='userbeyblade',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userbeyblade',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='userbeyratchet',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userbeyratchet',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='beybladebuild',
            name='assist_blade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='builds', to='api.beyassistblade'),
        ),
        migrations.CreateModel(
            name='BeybladeRelease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=250)),
                ('system', models.CharField(blank=True, choices=[('BX', 'Basic Line'), ('UX', 'Unique Line'), ('CX', 'Custom Line'), ('EX', 'Exclusive'), ('OUTRO', 'Outro')], max_length=20, null=True)),
                ('release_date', models.DateField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='beyblade/releases/')),
                ('image_url', models.URLField(blank=True, max_length=1000, null=True)),
                ('source_url', models.URLField(blank=True, max_length=1000, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assist_blade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='releases', to='api.beyassistblade')),
                ('bit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='releases', to='api.beybit')),
                ('blade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='releases', to='api.beyblade')),
                ('ratchet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='releases', to='api.beyratchet')),
                ('lock_chip', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='releases', to='api.beylockchip')),
            ],
            options={
                'verbose_name': 'Lançamento Beyblade',
                'verbose_name_plural': 'Lançamentos Beyblade',
                'ordering': ['code'],
            },
        ),
        migrations.AddField(
            model_name='beybladebuild',
            name='lock_chip',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='builds', to='api.beylockchip'),
        ),
        migrations.CreateModel(
            name='UserBeyAssistBlade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('acquired_at', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assist_blade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_by_users', to='api.beyassistblade')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_bey_assist_blades', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Assist Blade do usuário',
                'verbose_name_plural': 'Assist Blades do usuário',
                'ordering': ['assist_blade__name'],
                'constraints': [models.UniqueConstraint(fields=('user', 'assist_blade'), name='unique_user_bey_assist_blade')],
            },
        ),
        migrations.CreateModel(
            name='UserBeyLockChip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('acquired_at', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lock_chip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_by_users', to='api.beylockchip')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_bey_lock_chips', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Lock Chip do usuário',
                'verbose_name_plural': 'Lock Chips do usuário',
                'ordering': ['lock_chip__name'],
                'constraints': [models.UniqueConstraint(fields=('user', 'lock_chip'), name='unique_user_bey_lock_chip')],
            },
        ),
    ]
