# Generated by Django 5.2.8 on 2026-09-02 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_beyassistblade_beylockchip_alter_beybit_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beybit',
            name='bit_type',
            field=models.CharField(blank=True, choices=[('ATAQUE', 'Ataque'), ('DEFESA', 'Defesa'), ('STAMINA', 'Stamina'), ('BALANCE', 'Balance')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='beyblade',
            name='bey_type',
            field=models.CharField(blank=True, choices=[('ATAQUE', 'Ataque'), ('DEFESA', 'Defesa'), ('STAMINA', 'Stamina'), ('BALANCE', 'Balance')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='beyblade',
            name='spin',
            field=models.CharField(blank=True, choices=[('RIGHT', 'Direita'), ('LEFT', 'Esquerda'), ('DUAL', 'Dual Spin')], max_length=10, null=True),
        ),
    ]
