# Generated by Django 5.2.8 on 2026-09-02 17:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_alter_beybit_bit_type_alter_beyblade_bey_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BeyAssistBladeVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variant_name', models.CharField(max_length=150)),
                ('colors', models.JSONField(blank=True, default=list)),
                ('source_code', models.CharField(blank=True, max_length=80, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='beyblade/variants/assist-blades/')),
                ('image_url', models.URLField(blank=True, max_length=1000, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Variante de Assist Blade',
                'verbose_name_plural': 'Variantes de Assist Blade',
                'ordering': ['assist_blade__name', 'variant_name'],
            },
        ),
        migrations.CreateModel(
            name='BeyBitVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variant_name', models.CharField(max_length=150)),
                ('colors', models.JSONField(blank=True, default=list)),
                ('source_code', models.CharField(blank=True, max_length=80, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='beyblade/variants/bits/')),
                ('image_url', models.URLField(blank=True, max_length=1000, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Variante de Bit',
                'verbose_name_plural': 'Variantes de Bit',
                'ordering': ['bit__name', 'variant_name'],
            },
        ),
        migrations.CreateModel(
            name='BeyBladeVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variant_name', models.CharField(max_length=150)),
                ('colors', models.JSONField(blank=True, default=list)),
                ('source_code', models.CharField(blank=True, max_length=80, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='beyblade/variants/blades/')),
                ('image_url', models.URLField(blank=True, max_length=1000, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Variante de Blade',
                'verbose_name_plural': 'Variantes de Blade',
                'ordering': ['blade__name', 'variant_name'],
            },
        ),
        migrations.CreateModel(
            name='BeyLockChipVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variant_name', models.CharField(max_length=150)),
                ('colors', models.JSONField(blank=True, default=list)),
                ('source_code', models.CharField(blank=True, max_length=80, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='beyblade/variants/lock-chips/')),
                ('image_url', models.URLField(blank=True, max_length=1000, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Variante de Lock Chip',
                'verbose_name_plural': 'Variantes de Lock Chip',
                'ordering': ['lock_chip__name', 'variant_name'],
            },
        ),
        migrations.CreateModel(
            name='BeyRatchetVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variant_name', models.CharField(max_length=150)),
                ('colors', models.JSONField(blank=True, default=list)),
                ('source_code', models.CharField(blank=True, max_length=80, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='beyblade/variants/ratchets/')),
                ('image_url', models.URLField(blank=True, max_length=1000, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Variante de Ratchet',
                'verbose_name_plural': 'Variantes de Ratchet',
                'ordering': ['ratchet__name', 'variant_name'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='userbeyassistblade',
            name='unique_user_bey_assist_blade',
        ),
        migrations.RemoveConstraint(
            model_name='userbeybit',
            name='unique_user_bey_bit',
        ),
        migrations.RemoveConstraint(
            model_name='userbeyblade',
            name='unique_user_bey_blade',
        ),
        migrations.RemoveConstraint(
            model_name='userbeylockchip',
            name='unique_user_bey_lock_chip',
        ),
        migrations.RemoveConstraint(
            model_name='userbeyratchet',
            name='unique_user_bey_ratchet',
        ),
        migrations.AddField(
            model_name='beyassistbladevariant',
            name='assist_blade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='api.beyassistblade'),
        ),
        migrations.AddField(
            model_name='beybladebuild',
            name='assist_blade_variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='builds', to='api.beyassistbladevariant'),
        ),
        migrations.AddField(
            model_name='beybladerelease',
            name='assist_blade_variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='releases', to='api.beyassistbladevariant'),
        ),
        migrations.AddField(
            model_name='userbeyassistblade',
            name='variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_by_users', to='api.beyassistbladevariant'),
        ),
        migrations.AddConstraint(
            model_name='userbeyassistblade',
            constraint=models.UniqueConstraint(condition=models.Q(('variant__isnull', True)), fields=('user', 'assist_blade'), name='unique_user_bey_assist_without_variant'),
        ),
        migrations.AddConstraint(
            model_name='userbeyassistblade',
            constraint=models.UniqueConstraint(condition=models.Q(('variant__isnull', False)), fields=('user', 'variant'), name='unique_user_bey_assist_variant'),
        ),
        migrations.AddField(
            model_name='beybitvariant',
            name='bit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='api.beybit'),
        ),
        migrations.AddField(
            model_name='beybladebuild',
            name='bit_variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='builds', to='api.beybitvariant'),
        ),
        migrations.AddField(
            model_name='beybladerelease',
            name='bit_variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='releases', to='api.beybitvariant'),
        ),
        migrations.AddField(
            model_name='userbeybit',
            name='variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_by_users', to='api.beybitvariant'),
        ),
        migrations.AddConstraint(
            model_name='userbeybit',
            constraint=models.UniqueConstraint(condition=models.Q(('variant__isnull', True)), fields=('user', 'bit'), name='unique_user_bey_bit_without_variant'),
        ),
        migrations.AddConstraint(
            model_name='userbeybit',
            constraint=models.UniqueConstraint(condition=models.Q(('variant__isnull', False)), fields=('user', 'variant'), name='unique_user_bey_bit_variant'),
        ),
        migrations.AddField(
            model_name='beybladevariant',
            name='blade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='api.beyblade'),
        ),
        migrations.AddField(
            model_name='beybladebuild',
            name='blade_variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='builds', to='api.beybladevariant'),
        ),
        migrations.AddField(
            model_name='beybladerelease',
            name='blade_variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='releases', to='api.beybladevariant'),
        ),
        migrations.AddField(
            model_name='userbeyblade',
            name='variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_by_users', to='api.beybladevariant'),
        ),
        migrations.AddConstraint(
            model_name='userbeyblade',
            constraint=models.UniqueConstraint(condition=models.Q(('variant__isnull', True)), fields=('user', 'blade'), name='unique_user_bey_blade_without_variant'),
        ),
        migrations.AddConstraint(
            model_name='userbeyblade',
            constraint=models.UniqueConstraint(condition=models.Q(('variant__isnull', False)), fields=('user', 'variant'), name='unique_user_bey_blade_variant'),
        ),
        migrations.AddField(
            model_name='beylockchipvariant',
            name='lock_chip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='api.beylockchip'),
        ),
        migrations.AddField(
            model_name='beybladebuild',
            name='lock_chip_variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='builds', to='api.beylockchipvariant'),
        ),
        migrations.AddField(
            model_name='beybladerelease',
            name='lock_chip_variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='releases', to='api.beylockchipvariant'),
        ),
        migrations.AddField(
            model_name='userbeylockchip',
            name='variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_by_users', to='api.beylockchipvariant'),
        ),
        migrations.AddConstraint(
            model_name='userbeylockchip',
            constraint=models.UniqueConstraint(condition=models.Q(('variant__isnull', True)), fields=('user', 'lock_chip'), name='unique_user_bey_lock_without_variant'),
        ),
        migrations.AddConstraint(
            model_name='userbeylockchip',
            constraint=models.UniqueConstraint(condition=models.Q(('variant__isnull', False)), fields=('user', 'variant'), name='unique_user_bey_lock_variant'),
        ),
        migrations.AddField(
            model_name='beyratchetvariant',
            name='ratchet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='api.beyratchet'),
        ),
        migrations.AddField(
            model_name='beybladebuild',
            name='ratchet_variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='builds', to='api.beyratchetvariant'),
        ),
        migrations.AddField(
            model_name='beybladerelease',
            name='ratchet_variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='releases', to='api.beyratchetvariant'),
        ),
        migrations.AddField(
            model_name='userbeyratchet',
            name='variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_by_users', to='api.beyratchetvariant'),
        ),
        migrations.AddConstraint(
            model_name='userbeyratchet',
            constraint=models.UniqueConstraint(condition=models.Q(('variant__isnull', True)), fields=('user', 'ratchet'), name='unique_user_bey_ratchet_without_variant'),
        ),
        migrations.AddConstraint(
            model_name='userbeyratchet',
            constraint=models.UniqueConstraint(condition=models.Q(('variant__isnull', False)), fields=('user', 'variant'), name='unique_user_bey_ratchet_variant'),
        ),
        migrations.AddConstraint(
            model_name='beyassistbladevariant',
            constraint=models.UniqueConstraint(fields=('assist_blade', 'variant_name'), name='unique_bey_assist_blade_variant'),
        ),
        migrations.AddConstraint(
            model_name='beybitvariant',
            constraint=models.UniqueConstraint(fields=('bit', 'variant_name'), name='unique_bey_bit_variant'),
        ),
        migrations.AddConstraint(
            model_name='beybladevariant',
            constraint=models.UniqueConstraint(fields=('blade', 'variant_name'), name='unique_bey_blade_variant'),
        ),
        migrations.AddConstraint(
            model_name='beylockchipvariant',
            constraint=models.UniqueConstraint(fields=('lock_chip', 'variant_name'), name='unique_bey_lock_chip_variant'),
        ),
        migrations.AddConstraint(
            model_name='beyratchetvariant',
            constraint=models.UniqueConstraint(fields=('ratchet', 'variant_name'), name='unique_bey_ratchet_variant'),
        ),
    ]
