# Generated by Django 5.2.8 on 2026-09-03 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_beyassistbladevariant_beybitvariant_beybladevariant_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='beyassistbladevariant',
            options={'ordering': ['assist_blade__name', '-is_default', 'variant_name'], 'verbose_name': 'Variante de Assist Blade', 'verbose_name_plural': 'Variantes de Assist Blade'},
        ),
        migrations.AlterModelOptions(
            name='beybitvariant',
            options={'ordering': ['bit__name', '-is_default', 'variant_name'], 'verbose_name': 'Variante de Bit', 'verbose_name_plural': 'Variantes de Bit'},
        ),
        migrations.AlterModelOptions(
            name='beybladerelease',
            options={'ordering': ['code', 'slot_number', 'name'], 'verbose_name': 'Lançamento Beyblade', 'verbose_name_plural': 'Lançamentos Beyblade'},
        ),
        migrations.AlterModelOptions(
            name='beybladevariant',
            options={'ordering': ['blade__name', '-is_default', 'variant_name'], 'verbose_name': 'Variante de Blade', 'verbose_name_plural': 'Variantes de Blade'},
        ),
        migrations.AlterModelOptions(
            name='beylockchipvariant',
            options={'ordering': ['lock_chip__name', '-is_default', 'variant_name'], 'verbose_name': 'Variante de Lock Chip', 'verbose_name_plural': 'Variantes de Lock Chip'},
        ),
        migrations.AlterModelOptions(
            name='beyratchetvariant',
            options={'ordering': ['ratchet__name', '-is_default', 'variant_name'], 'verbose_name': 'Variante de Ratchet', 'verbose_name_plural': 'Variantes de Ratchet'},
        ),
        migrations.AddField(
            model_name='beyassistbladevariant',
            name='catalog_key',
            field=models.CharField(blank=True, max_length=300, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='beyassistbladevariant',
            name='edition_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='beyassistbladevariant',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='beybitvariant',
            name='catalog_key',
            field=models.CharField(blank=True, max_length=300, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='beybitvariant',
            name='edition_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='beybitvariant',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='beybladerelease',
            name='edition_name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='beybladerelease',
            name='product_name',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='beybladerelease',
            name='product_type',
            field=models.CharField(blank=True, choices=[('STARTER', 'Starter'), ('BOOSTER', 'Booster'), ('RANDOM_BOOSTER', 'Random Booster'), ('SET', 'Set'), ('DECK_SET', 'Deck Set'), ('LIMITED', 'Limitado / Exclusivo'), ('PRIZE', 'Prêmio / Campanha'), ('OTHER', 'Outro')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='beybladerelease',
            name='slot_number',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='beybladerelease',
            name='slug',
            field=models.SlugField(blank=True, max_length=300, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='beybladerelease',
            name='source_item_id',
            field=models.CharField(blank=True, db_index=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='beybladevariant',
            name='catalog_key',
            field=models.CharField(blank=True, max_length=300, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='beybladevariant',
            name='edition_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='beybladevariant',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='beylockchipvariant',
            name='catalog_key',
            field=models.CharField(blank=True, max_length=300, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='beylockchipvariant',
            name='edition_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='beylockchipvariant',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='beyratchetvariant',
            name='catalog_key',
            field=models.CharField(blank=True, max_length=300, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='beyratchetvariant',
            name='edition_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='beyratchetvariant',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='beybladerelease',
            name='code',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
        migrations.AddConstraint(
            model_name='beybladerelease',
            constraint=models.UniqueConstraint(condition=models.Q(('source_url__isnull', False), ('source_item_id__isnull', False)), fields=('source_url', 'source_item_id'), name='unique_beyblade_source_item'),
        ),
    ]
