# Generated by Django 5.2.8 on 2026-09-12 01:42

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_alter_beyassistbladevariant_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pokemonhalloffame',
            name='sprite_1',
        ),
        migrations.RemoveField(
            model_name='pokemonhalloffame',
            name='sprite_2',
        ),
        migrations.RemoveField(
            model_name='pokemonhalloffame',
            name='sprite_3',
        ),
        migrations.RemoveField(
            model_name='pokemonhalloffame',
            name='sprite_4',
        ),
        migrations.RemoveField(
            model_name='pokemonhalloffame',
            name='sprite_5',
        ),
        migrations.RemoveField(
            model_name='pokemonhalloffame',
            name='sprite_6',
        ),
        migrations.AddField(
            model_name='pokemonhalloffame',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pokemonhalloffame',
            name='pokemon_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='api.pokemon'),
        ),
        migrations.AddField(
            model_name='pokemonhalloffame',
            name='pokemon_1_shiny',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pokemonhalloffame',
            name='pokemon_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='api.pokemon'),
        ),
        migrations.AddField(
            model_name='pokemonhalloffame',
            name='pokemon_2_shiny',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pokemonhalloffame',
            name='pokemon_3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='api.pokemon'),
        ),
        migrations.AddField(
            model_name='pokemonhalloffame',
            name='pokemon_3_shiny',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pokemonhalloffame',
            name='pokemon_4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='api.pokemon'),
        ),
        migrations.AddField(
            model_name='pokemonhalloffame',
            name='pokemon_4_shiny',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pokemonhalloffame',
            name='pokemon_5',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='api.pokemon'),
        ),
        migrations.AddField(
            model_name='pokemonhalloffame',
            name='pokemon_5_shiny',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pokemonhalloffame',
            name='pokemon_6',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='api.pokemon'),
        ),
        migrations.AddField(
            model_name='pokemonhalloffame',
            name='pokemon_6_shiny',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='pokemonhalloffame',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pokemon_hall_of_fame', to=settings.AUTH_USER_MODEL),
        ),
    ]
