# Generated by Django 5.2.8 on 2026-09-12 15:27

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_remove_pokemonhalloffame_sprite_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='pokemon_trainer_photo',
            field=models.ImageField(blank=True, null=True, upload_to=api.models.pokemon_trainer_photo_path),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='pokemon_trainer_photo_position',
            field=models.CharField(default='50% 50%', max_length=50),
        ),
    ]
