# Generated by Django 5.2.8 on 2026-09-12 17:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_userprofile_pokemon_trainer_photo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='pokemon_favorite_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='api.pokemon'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='pokemon_favorite_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='api.pokemon'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='pokemon_favorite_3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='api.pokemon'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='pokemon_favorite_4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='api.pokemon'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='pokemon_favorite_5',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='api.pokemon'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='pokemon_favorite_6',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='api.pokemon'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='pokemon_favorite_mechanic',
            field=models.CharField(blank=True, choices=[('MEGA_EVOLUTION', 'Mega Evolução'), ('Z_MOVE', 'Z-Move'), ('DYNAMAX_GIGANTAMAX', 'Dynamax / Gigantamax'), ('TERASTAL', 'Terastal')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='pokemon_tcg_league_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
