# Generated by Django 5.2.8 on 2026-09-14 15:57

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_userprofile_pokemon_favorite_1_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VGCAbility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_id', models.PositiveIntegerField(blank=True, null=True, unique=True)),
                ('name', models.CharField(max_length=120, unique=True)),
                ('display_name', models.CharField(blank=True, max_length=120, null=True)),
                ('effect', models.TextField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Habilidade VGC',
                'verbose_name_plural': 'Habilidades VGC',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='VGCItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_id', models.PositiveIntegerField(blank=True, null=True, unique=True)),
                ('name', models.CharField(max_length=120, unique=True)),
                ('display_name', models.CharField(blank=True, max_length=120, null=True)),
                ('sprite_url', models.URLField(blank=True, max_length=1000, null=True)),
                ('effect', models.TextField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Item VGC',
                'verbose_name_plural': 'Itens VGC',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='VGCMove',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_id', models.PositiveIntegerField(blank=True, null=True, unique=True)),
                ('name', models.CharField(max_length=120, unique=True)),
                ('display_name', models.CharField(blank=True, max_length=120, null=True)),
                ('move_type', models.CharField(blank=True, max_length=50, null=True)),
                ('damage_class', models.CharField(blank=True, max_length=20, null=True)),
                ('power', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('accuracy', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('pp', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('priority', models.SmallIntegerField(default=0)),
                ('effect', models.TextField(blank=True, null=True)),
                ('effect_chance', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('generation', models.CharField(blank=True, max_length=50, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Golpe VGC',
                'verbose_name_plural': 'Golpes VGC',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='pokemon',
            name='base_attack',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pokemon',
            name='base_defense',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pokemon',
            name='base_hp',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pokemon',
            name='base_special_attack',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pokemon',
            name='base_special_defense',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pokemon',
            name='base_speed',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='VGCTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('regulation', models.CharField(blank=True, max_length=50, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vgc_teams', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Equipe VGC',
                'verbose_name_plural': 'Equipes VGC',
                'ordering': ['-updated_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VGCPokemonBuild',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(6)])),
                ('nickname', models.CharField(blank=True, max_length=100, null=True)),
                ('is_shiny', models.BooleanField(default=False)),
                ('level', models.PositiveSmallIntegerField(default=50, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('tera_type', models.CharField(blank=True, max_length=50, null=True)),
                ('nature', models.CharField(choices=[('HARDY', 'Hardy'), ('LONELY', 'Lonely'), ('BRAVE', 'Brave'), ('ADAMANT', 'Adamant'), ('NAUGHTY', 'Naughty'), ('BOLD', 'Bold'), ('DOCILE', 'Docile'), ('RELAXED', 'Relaxed'), ('IMPISH', 'Impish'), ('LAX', 'Lax'), ('TIMID', 'Timid'), ('HASTY', 'Hasty'), ('SERIOUS', 'Serious'), ('JOLLY', 'Jolly'), ('NAIVE', 'Naive'), ('MODEST', 'Modest'), ('MILD', 'Mild'), ('QUIET', 'Quiet'), ('BASHFUL', 'Bashful'), ('RASH', 'Rash'), ('CALM', 'Calm'), ('GENTLE', 'Gentle'), ('SASSY', 'Sassy'), ('CAREFUL', 'Careful'), ('QUIRKY', 'Quirky')], default='SERIOUS', max_length=20)),
                ('iv_hp', models.PositiveSmallIntegerField(default=31, validators=[django.core.validators.MaxValueValidator(31)])),
                ('iv_attack', models.PositiveSmallIntegerField(default=31, validators=[django.core.validators.MaxValueValidator(31)])),
                ('iv_defense', models.PositiveSmallIntegerField(default=31, validators=[django.core.validators.MaxValueValidator(31)])),
                ('iv_special_attack', models.PositiveSmallIntegerField(default=31, validators=[django.core.validators.MaxValueValidator(31)])),
                ('iv_special_defense', models.PositiveSmallIntegerField(default=31, validators=[django.core.validators.MaxValueValidator(31)])),
                ('iv_speed', models.PositiveSmallIntegerField(default=31, validators=[django.core.validators.MaxValueValidator(31)])),
                ('ev_hp', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(252)])),
                ('ev_attack', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(252)])),
                ('ev_defense', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(252)])),
                ('ev_special_attack', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(252)])),
                ('ev_special_defense', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(252)])),
                ('ev_speed', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(252)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ability', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pokemon_builds', to='api.vgcability')),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pokemon_builds', to='api.vgcitem')),
                ('move_1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='api.vgcmove')),
                ('move_2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='api.vgcmove')),
                ('move_3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='api.vgcmove')),
                ('move_4', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='api.vgcmove')),
                ('pokemon', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vgc_builds', to='api.pokemon')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pokemon_builds', to='api.vgcteam')),
            ],
            options={
                'verbose_name': 'Build de Pokémon VGC',
                'verbose_name_plural': 'Builds de Pokémon VGC',
                'ordering': ['team_id', 'slot'],
                'constraints': [models.UniqueConstraint(fields=('team', 'slot'), name='unique_vgc_team_slot')],
            },
        ),
    ]
