# Generated by Django 5.2.8 on 2026-09-15 16:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_vgcability_vgcitem_vgcmove_pokemon_base_attack_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=220)),
                ('slug', models.SlugField(max_length=250, unique=True)),
                ('category', models.CharField(choices=[('NEWS', 'Notícias / Novidades'), ('REVIEW', 'Reviews'), ('RECOMMENDATION', 'Indicações'), ('BEYBLADE', 'Beyblade'), ('POKEMON', 'Pokémon'), ('BOARDGAME', 'Jogos de tabuleiro'), ('GUIDE', 'Guias'), ('COLLECTION', 'Diário do acervo'), ('PROJECT', 'Projetos pessoais')], default='NEWS', max_length=20)),
                ('excerpt', models.TextField(blank=True, max_length=500)),
                ('content', models.TextField()),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='posts/covers/')),
                ('cover_url', models.URLField(blank=True, max_length=1000, null=True)),
                ('is_published', models.BooleanField(default=False)),
                ('is_featured', models.BooleanField(default=False)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Publicação',
                'verbose_name_plural': 'Publicações',
                'ordering': ['-published_at', '-created_at'],
            },
        ),
    ]
